// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpnbeGCBdAsX2GBTiO07HyYplXT6GSZfI',
    appId: '1:678186320498:web:e14fcc913e55d97badf8eb',
    messagingSenderId: '678186320498',
    projectId: 'fourth-physics-450708-s2',
    authDomain: 'fourth-physics-450708-s2.firebaseapp.com',
    storageBucket: 'fourth-physics-450708-s2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOldVNztGQfPu7vyqJYt-4LkSjUMtrcCs',
    appId: '1:678186320498:android:d2bf57842c9ff425adf8eb',
    messagingSenderId: '678186320498',
    projectId: 'fourth-physics-450708-s2',
    storageBucket: 'fourth-physics-450708-s2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwbHfFfaoKzhpFvVg5D6NpxufE89V1594',
    appId: '1:678186320498:ios:bed28867ab31712cadf8eb',
    messagingSenderId: '678186320498',
    projectId: 'fourth-physics-450708-s2',
    storageBucket: 'fourth-physics-450708-s2.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwbHfFfaoKzhpFvVg5D6NpxufE89V1594',
    appId: '1:678186320498:ios:bed28867ab31712cadf8eb',
    messagingSenderId: '678186320498',
    projectId: 'fourth-physics-450708-s2',
    storageBucket: 'fourth-physics-450708-s2.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpnbeGCBdAsX2GBTiO07HyYplXT6GSZfI',
    appId: '1:678186320498:web:b615db05c14f4e63adf8eb',
    messagingSenderId: '678186320498',
    projectId: 'fourth-physics-450708-s2',
    authDomain: 'fourth-physics-450708-s2.firebaseapp.com',
    storageBucket: 'fourth-physics-450708-s2.firebasestorage.app',
  );
}
